-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th4 01, 2018 lúc 06:25 PM
-- Phiên bản máy phục vụ: 10.1.31-MariaDB
-- Phiên bản PHP: 7.2.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `food`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `monan2`
--

CREATE TABLE `monan2` (
  `id` int(3) NOT NULL,
  `ten` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `img` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `nguyenlieu` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `cachlam` varchar(10000) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `monan2`
--

INSERT INTO `monan2` (`id`, `ten`, `img`, `type`, `nguyenlieu`, `cachlam`) VALUES
(1, 'Cơm sườn bò', 'image/anh1.jpg', 'Món ăn miền Bắc', '4 miếng sườn cốt lết ngon ( lựa miếng có mỡ khi nướng thịt sẽ mềm hơn) |\r\n1 lon gạo tấm gạo tấm |\r\nTỏi bằm |\r\nHành lá |\r\nMật ong\r\n1 trái cà chua, 1 trái dưa leo |\r\n1 ít lá dứa |\r\nNước màu ', 'Cho cơm tấm vào nồi nấu chung với lá dứa|\r\nCho thịt nướng lên bếp than, cho đến khi thịt chin đỏ 2 mặt thì bỏ xuống.|\r\nLàm mỡ hành: cho dầu ăn vào chảo nóng lên,phi  cho hành thơm, vẫn giữ màu xanh tươi thì bỏ xuống|\r\nLàm nước mắm: cho 1 muỗng nước mắm, 2 muỗng đường, 1 miếng chanh, cho 3 muỗng nước ấm vào khuấy đều lên. Cho thêm đồ chua, ớt nếu bạn thích ăn cay|\r\nĐể hoàn thành món cơm tấm sườn nướng  ta chỉ cần cho cơm tấm ra dĩa, cho mỡ hành lên, thịt sườn để lên. Trang trí thêm với dưa leo, cà chua.\r\n\r\nChúc các bạn ngon miệng!'),
(2, 'Bún Sương', 'image/bunxuong.jpg', 'Món ăn miền Trung', '500g tôm tươi tách vỏ|\r\n10 con tôm hấp, lột vỏ để riêng|\r\n1 kg xương ống heo|\r\n1 gói bún khô|\r\nGiá hẹ|\r\nHạt màu điều', 'Nấu nước xương: cho xương vào nồi hầm cho ra nước ngọt.|\r\nLàm chả tôm|\r\nCho nước xương qua nồi nấu nước lèo. Cho chả tôm vào luộc lại. Cho nước màu điều thêm đẹp mắt. Nêm nếm gia vị vừa ăn.|\r\nCho bún ra tô, 2 con tôm lột vỏ,  3-4 miếng chả tôm, hành ngò, giá hẹ, chan nước dùng lên là bạn đã hoàn tất món bún suông.|\r\n\r\nNgoài ra mọi người còn thường cho vào món bún suông thịt ba rọi luộc cắt mỏng.\r\n\r\nChúc các bạn ngon miệng!'),
(3, 'Nem rán', 'image/Nemran.jpg', 'Món ăn miền Bắc', 'Thịt vai: 400g (nên chọn thịt sấn vai có cả mỡ)\r\n\r\nHành tây: 1 củ nhỏ|\r\n\r\nGiá đỗ: 150gr|\r\n\r\nCà rốt: 1 củ nhỏ|\r\n\r\nSu hào: Nửa củ|\r\n\r\n100g miến, vài cái nấm hương, mộc nhĩ|\r\n\r\n2 quả trứng|\r\n\r\nHành hoa, rau mùi, hạt tiêu, mắm, gia vị|\r\n\r\nVỏ bánh đa nem: 35 – 40 cái', 'Cho tất cả các nguyên liệu làm nem rán đã chuẩn bị ở các bước trên vào một âu lớn. Cho thêm một thìa ăn cơm dầu ăn, thêm hạt tiêu, mắm, gia vị, hạt nêm. Đập thêm 2 quả trứng vào âu.|\r\n Trải bánh đa nem ra (nên trải trên thớt hoặc mâm bằng phẳng, dùng tay nhúng vào bia hoặc dấm để vỏ bánh được giòn rồi xoa đều quanh mặt chiếc bánh)|\r\n\r\nXúc một lượng nhân thịt nem đặt vào bánh đa, cuộn 1 vòng cho kín rồi gập hai đầu hai bên lại.|\r\n\r\nCuộn tiếp vòng nữa cho đến hết chiếc bánh đa nem là được.|\r\n\r\nLưu ý khi cuốn nem bạn nên cuốn tất cả các nem một lượng bằng nhau, cuộn chặt tay, để những chiếc nem được đều nhau và khi rán nem không bị vỡ vụn.|\r\n\r\nĐun sôi dầu ăn đến lúc già, cho nem vào rán qua, khi ăn sẽ rán nem lại 1 lần nữa cho chín vàng đều là được.|\r\n\r\nKhi rán nem bạn rán cho một mặt vàng đều rồi lật sang mặt dưới rán đến khi nem chuyển màu vàng cánh gián.|\r\n\r\nMón nem rán ngon nhất khi thưởng thức nóng. Một yếu tố nữa quyết định đến món nem rán có ngon hay không là nước chấm nem. Cách pha nước chấm nem chuẩn nhất là theo công thức: 1 chua - 1 ngọt - 1 mắm - 4 nước.|\r\n\r\nTức là khi pha nước chấm nem thì bạn dùng 1 chiếc thìa nhỏ ăn cơm để đong các nguyên liệu này và để có được một bát nước chấm ngon, bạn cần 1 thìa nước cốt chanh - 1 thìa đường - 1 thìa mắm - 4 thìa nước lọc.|\r\n\r\nKhuấy lên cho các nguyên liệu này hòa tan vào nhau thành một dung dịch đồng nhất. Nếu đường vẫn còn lắng ở đáy mà chưa tan thì bát nước chấm nem của bạn chưa đạt được độ hài hòa và chuẩn vị.|\r\n\r\nĐến khi ăn thì bạn cho tỏi ớt đã băm nhuyễn và rắc thêm chút hạt tiêu vào là đã có được bát chấm nem rán đạt yêu cầu.\r\n\r\nChúc các bạn thành công với cách làm nem rán giòn rụm này nhé!'),
(4, 'Bánh xèo', 'image/banhxeo.jpg', 'Món ăn miền Nam', 'Bột gạo: 400g|\r\nThịt heo: 200g|\r\nTôm: 150g|\r\nNước cốt dừa: 50ml|\r\nBia: 100 ml|\r\nHành, tỏi, ớt, gừng|\r\nNấm, rau sống, giá đỗ|\r\nBột nghệ, nước mắm, gia vị, tiêu', 'Cho bột gạo vào bát cùng 1 thìa cà phê nhỏ bột nghệ trộn đều.|\r\n\r\nPha khoảng 250ml nước, 100ml bia với 50ml nước cốt dừa dùng để hòa vào bát bột. Có thể bạn cảm thấy lạ khi pha bột với bia, nhưng bia lại có tác dụng giúp bánh xèo giòn lâu hơn đây chính là bí quyết của cách làm bánh xèo ngon.|\r\n\r\nRồi từ từ đổ nước vừa pha vào bát bột, khuấy đều bát bột để có 1 hỗn hợp lỏng không bị vón cục. Sau đó thái vào 1 ít hành lá rồi để trong khoảng 30p trước khi làm bánh.|\r\nHành, tỏi bóc vỏ thái nhỏ|\r\n\r\nTôm cắt bỏ đầu, chân rồi rửa sạch và ướp với 1 ít muối, gừng, tỏi, hành băm nhỏ |\r\nThịt rửa sạch rồi thái miếng mỏng, ướp với mắm hạt nêm, tiêu, hành tỏi băm.|\r\n\r\nNấm ngâm vào nước ấm cho nở, cắt bỏ chân rửa sạch rồi thái sợi.|\r\n\r\nRau sống nhặt bỏ lá úa ngâm qua nước muối rồi rửa sạch, vớt ra để ráo nước.|\r\nĐun nóng chảo cho dầu ăn vào rồi đổ thịt vào săn lại, tiếp đến cho tôm và nấm vào xào cùng, nêm nếm lại cho vừa ăn sau đó đổ ra bát.|\r\nTráng bánh nên sử dụng loại chảo lòng sâu khi tráng bánh sẽ mỏng đều hơn.|\r\n\r\nCho chảo lên bếp đun nóng dầu ăn, đổ bột láng đều xung quanh bề mặt chảo cho thật mỏng, rồi đậy nắp vào khoảng chừng nửa phút.|\r\nMở nắp rồi cho hỗn hợp tôm , nấm và thịt vừa xào vào thêm ít giá đỗ rải đều lên bề mặt bánh rồi lại đậy nắp chảo lại khoảng 2p nữa cho bánh chín.|\r\n\r\nGập đôi bánh chờ đến khi bánh vàng đều cả 2 mặt, chín giòn là được.\r\n\r\nBánh xèo có màu vàng ươm, vỏ bánh mỏng giòn, thơm phức mùi tôm thịt khi ăn bánh kèm thêm rau sống và nước mắm chua cay ngọt thật hấp dẫn. Hy vọng với cách làm bánh xèo này bạn có thể tự tay làm được những chiếc bánh xèo thơm ngon tại nhà để cùng gia đình thưởng thức nhé!\r\n\r\n'),
(5, 'Bánh Da Lợn', 'image/banhdalon.jpg', 'Món ăn miền Bắc', ' \r\n300 gram đậu xanh|\r\n150 gram bột năng|\r\n150 gram bột gạo|\r\n200 gram đường|\r\n100 gram lá dứa|\r\n200 ml nước cốt dừa|\r\n1,2 lít nước lọc', 'Đậu xanh rửa sạch đãi vỏ, ngâm với nước trong 3 tiếng. Bạn có thể pha 1 muỗng cafe muối vào nước ngâm đậu xanh cho sạch. Ngâm xong, cho đậu xanh vào nồi cơm điện nấu chín.|\r\nNấu chín xong, cho đậu xanh vào máy xay sinh tố, xay nhuyễn. Hòa 500 ml nước lọc và 100 gram đường vào phần đậu đã xay nhuyễn, trộn đều thật đều sao cho đường tan trong hỗn hợp nước.|\r\nLá dứa rửa sạch, thái khúc nhỏ cho dễ lấy nước. Cho hết phần lá dứa thái nhỏ vào máy xay sinh tố, chắt lấy nước. Bạn có thể dùng dụng cụ rây bột để lấy nước lá dứa nhanh hơn.|\r\nSau khi xay lấy nước lá dứa, bạn cho tiếp 500 ml nước còn lại và 100 gram đường, khuấy đều cho hòa tan.|\r\n\r\n Cho bột năng và bột gạo vào lọc qua dụng cụ rây bột cho vào 200 ml nước lọc. Khuấy đều sao cho hai loại bột hòa tan với nhau.|\r\n Cho 1/2 lượng nước bột vào phần đậu xanh, khuấy đều. Đổ phần đầu xanh qua dụng cụ rây bột để lấy nước, bỏ bã. Sau đó mới cho nước cốt dừa vào, khuấy hòa tan.|\r\n\r\nCho 1/2 lượng nước bột còn lại vào phần nước lá dứa, trộn đều.|\r\nChuẩn bị nồi hấp cách thủy cho lên bếp, riêng khuôn bánh ta dùng miếng bông gòn quết một lớp dầu ăn lên mặt đáy khuôn và cạnh khuôn để sau khi bánh chín, lấy ra khỏi khuôn được dễ dàng.|\r\nKhi nồi hấp sôi, cho 1 lớp phần đậu xanh vào trước, khoảng 2 cm chiều dài khuôn bánh. Đậy vung, chờ 5-7 phút để bánh đông lại, cho tiếp 1 lớp dày 2 cm nước lá dứa vào khuôn bánh, đậy vung. Thời gian chờ phần lá dứa chín sẽ lâu hơn phần đậu xanh lúc đầu, nên bạn chờ khoảng 10 phút mở vung ra đổ lớp đậu xanh lên trên mặt lá dứa.|\r\n\r\nCứ như thế tương tự, ta đổ hai lớp xen kẽ nhau đến khi hết bột thì thôi, nhớ là thời gian cho lớp bánh trên sẽ lâu hơn lớp bánh dưới. Canh giờ cho chính xác để bánh chín ngon, có độ đàn hồi cao, ăn dẻo và hương thơm phưng phức.\r\nBánh da lợn chín ta đổ khuôn bánh ra, dùng sợi chỉ xắt bánh hoặc dùng dao cũng được, cắt thành miếng và thưởng thức!'),
(6, 'Sườn Kho Tộ', 'image/suon-kho-to-1-300x235.jpg', 'Món ăn miền Bắc', '500g sườn non|\r\n1 củ hành khô|\r\n2-3 tép tỏi|\r\nĐường|\r\nNước mắm|\r\nGia vị|\r\nDầu ăn', 'Sườn non sau khi rửa sạch và cho vào nồi cùng với ít nước và nấu đến khi nước sôi thì tắt bếp, vớt sườn ra để ráo.|\r\nHành và tỏi bỏ vỏ và băm nhuyễn.|\r\nBắc chảo lên bếp làm nóng dầu ăn và cho hành và tỏi bâm nhuyễn vào phi thơm, rồi bạn cho sườn vào xào và nêm nếm gia vị, khi sườn dậy mùi thơm thì tắt bếp.|\r\nLấy một chiếc nồi khác và cho vào 1/2 muỗng canh nước lọc + 1/2 muỗng canh đường, đun trên lửa nhỏ đến khi hỗn hợp chuyển màu cánh gián thì cho sườn vào và đảo đều tay cho sườn thấm nước trong nồi.|\r\nĐể lửa riu riu hầm đến khi thịt sườn mềm và nước sền sệt là được.|\r\nTắt bếp rồi dọn sườn ra dĩa và dùng nóng với cơm trắng và canh.\r\n'),
(7, 'Đậu Hũ Non Sốt Cà Chua ', 'image/Đậu-hũ-non-sốt-cà-chua.jpg', 'Món ăn miền Bắc', 'Đậu hũ non|\r\nNấm mèo|\r\n1 trái cà chua|\r\nHành lá|\r\nBột năng', 'Đậu hũ non rửa sạch và giã nhuyễn|\r\nTrộn đậu hũ non giã với nấm mèo cắt sợi + bột năng + hạt nêm\r\nlấy một cái chén sạch và cho tất cả hỗn hợp đậu hũ non vào ép chặt\r\nchuẩn bị nồi hấp và cho đậu hũ vào hấp cách thủy|\r\nCà chua rửa sạch, băm nhuyễn.|\r\nBắc chảo lên bếp và làm nóng dầu thực vật rồi cho cà chua vào xào mềm. Nêm nếm gia vị cho vừa ăn.|\r\nBột năng pha nước và cho vào chảo để cho sốt cà chua sền sệt lại .|\r\nLấy đậu hũ đã hấp chín ra khỏi chén và cho nước sốt lên trên , hành lá Cắt nhỏ và rải lên trên\r\nDùng nóng với cơm trắng'),
(8, 'Bún Bề Bề', 'image/bunbebe.jpg', 'Món ăn miền Bắc', 'Bề bề: 500gr|\r\nBún tươi: 1kg|\r\nXương đuôi lợn: 400gr|\r\nĐậu phụ: 3 bìa|\r\nRau cần: 1 mớ nhỏ (hoặc dùng rau cải ngọt tùy vào sở thích)|\r\nCà chua: 2 quả to|\r\n\r\nHành hoa, mùi tàu (hoặc thì là), hành khô|\r\n\r\nTương ớt, chanh, mắm, hạt nêm, gia vị', 'Xương đuôi lợn rửa sạch, cho vào nồi, đổ ngập nước, đun sôi trong 3-4 phút, chắt bỏ nước luộc xương, rửa vài lần với nước lã cho sạch bọt bẩn. Cho xương trở lại nồi, đổ nước, ninh nhừ xương để làm nước dùng.|\r\nBề bề cho vào rổ, xóc đều dưới vòi nước chảy để rửa sạch. Cho bề bề vào nồi, thêm 1 mẩu gừng và 1 củ hành đập dập, cho nồi bề bề lên bếp, luộc chín bề bề (không cần đổ nước vì trong lúc đun bề bề sẽ tự ra nước).|\r\nDùng kéo cắt bỏ đầu và 2 bên mép dọc thân bề bề, bóc bỏ phần vỏ cứng của bề bề, lột lấy phần thịt bề bề.|\r\nĐậu phụ cắt miếng nhỏ, rán chín vàng các mặt.|\r\n Rau cần nhặt rửa sạch, để ráo nước rồi thái khúc ngắn.|\r\nHành khô thái mỏng, cho vào chảo dầu vừa rán đậu, phi cho hành bắt đầu chuyển màu hơi vàng thì vớt ngay ra (với sức nóng của dầu, hành sẽ tiếp tục vàng hơn và khi nguội sẽ giòn).|\r\nPhần đầu và vỏ của bề bề đem giã (hoặc xay) nhỏ, lọc lấy nước cho vào nồi nước ninh xương.|\r\nChần bún qua nước nóng rồi cho vào từng bát to. Rau cần cũng đem chần trong nồi nước dùng cho chín tới, rồi đem xếp lên 1 góc của bát bún.|\r\nGạn bớt dầu ăn vừa phi hành ra bát, cho cà chua thái miếng vào xào cho cà chua chín, dùng thìa dằm nhuyễn. Đổ cà chua đã xào chín vào nồi nước dùng. Nêm mắm, gia vị hạt nêm cho vừa miệng.|\r\nXếp đậu, hành, mùi tàu (hoặc thì là) thái nhỏ, bề bề, hành phi vào bát bún.|\r\nCuối cùng đem chan nước dùng vào bún bề bề và thưởng thức.'),
(9, 'Nem chua', 'image/nemchua.jpg', 'Món ăn miền Nam', 'Thịt thăn lợn: 600g|\r\nThịt thăn bò: 300g|\r\nBì lợn: 300g|\r\nThính gạo: 2 thìa ăn cơm|\r\nĐường: 50g|\r\nGia vị làm nem chua của Thái (Nam powder seasoning mix): 1 gói|\r\nHạt nêm: 2 thìa cà phê|\r\nNước mắm ngon: 2 thìa ăn cơm|\r\nRượu nếp: 2 thìa cà phê|\r\nHạt tiêu: 1 thìa cà phê|\r\nTỏi (5 củ to), ớt, bột canh, màng bọc thức ăn (hoặc lá chuối)', 'Bì lợn mua về cạo rửa thật sạch, cho vào nồi luộc chín tới với một ít muối, sau đó thái sợi thật nhỏ (nếu không có thời gian thì mua bì lợn thái sẵn ở những hàng bán nem thính tại các chợ)|\r\nThịt bò và thịt lợn rửa sạch với nước đun sôi có pha chút muối loãng.|\r\nTỏi bóc vỏ, một nửa đem băm nhuyễn còn một nữa thái lát mỏng.|\r\nCho tất cả các nguyên liệu: thịt xay, bì lợn, thính gạo, đường, mắm, rượu, hạt tiêu, tỏi phi vàng, tỏi sống băm nhỏ, hạt nêm, bột canh, 1 gói gia vị làm nem chua (gói to) vào chung 1 âu lớn.|\r\n Dùng màng bọc thực phẩm bọc lấy miệng âu rồi để khoảng 1 tiếng lại cho tiếp 1 gói gia vị làm nem chua nhỏ (gói nhỏ có trong gói lớn) vào trộn đều.|\r\nKhi này hãy nhanh tay cho thịt vào khuôn làm giò xào rồi vặn vít thật chặt để cho thịt kết dính với nhau.|\r\nĐể khuôn nem chua ở nhiệt độ phòng, chỗ thoáng mát trong tầm 24 tiếng.'),
(10, 'Hủ Tiếu', 'image/hutieu.jpg', 'Món ăn miền Nam', ' Khoảng 2kg xương ống heo, xương cổ|\r\n1 đùi heo chặt nhỏ|\r\n500gr thịt nạc vai bằm nhỏ|\r\n1 kg sườn heo, cắt miếng vừa ăn|\r\n3 con mực khô bằng nửa bàn tay, rang vàng|\r\n200gr tôm khô (loại nhỏ) rửa sạch|\r\n1 củ cải trắng|\r\n1 củ hành tây|\r\n1 bó hành lá|\r\nChanh, giá, tương ớt, ớt ngâm chua|\r\nSợi hủ tiếu|\r\nTóp mỡ, hành phi|\r\n1 sợi củ cải muối loại màu nâu đậm|\r\nĐường phèn, bột ngọt, tiêu', 'Xương rửa sạch, luộc sơ bỏ ra rửa lại cho sạch. Cho xương vào nồi, nước ngập mặt xương khoảng hơn 2 đốt ngón tay. Cho chút muối vào, đun sôi, hớt bọt rồi để lửa vừa ninh xương.|\r\n\r\nCho Sườn heo, giò heo cắt miếng cho vào nồi hầm xương luộc Nấu tỉ lệ xương và nước theo tỉ lê 1:3 (gia giảm lượng nước tùy ý). Xương bỏ vào đun sôi chừng 10-15 phút, vớt bọt liên tục rồi hạ lửa nhỏ riu riu để ninh trong 2-3 tiếng.|\r\n\r\nTôm khô cho vào giỏ kim loại nấu trong nồi nước dùng cho thơm, khoảng 1h vớt ra để ráo, bắc dầu bỏ tôm vào chiên cho tôm vàng rụm, thêm tiêu muối, bột ngọt nêm vừa ăn.|\r\n\r\nHành tây bổ múi cau , bỏ củ cải trắng, củ cải muối, khô mực nướng, tôm khô cho vào nồi nước lèo. Đợi sôi trở lại, tiếp tục vớt bọt.|\r\nNêm gia vị muối, đường phèn, bột ngọt, nước mắm. Để lửa riu riu khoảng 3 tiếng, không nên hầm xương quá lâu sẽ có mùi hôi.|\r\n\r\nThịt heo xay cho vào xoong nhỏ, thêm chút cải bắc thảo, tiêu, bột ngọt, muối, trộn đều, cho độ khoảng 2 thià muôi canh nấu sôi lên chừng 5 phút là được, đủ cho thịt săn và vừa ăn đừng để lâu quá sẽ bã thịt không ngon.|\r\n\r\n “Bí quyết” khâu quan trọng nhất để có mùi thơm vị ngọt tự nhiên đặc trưng của nước lèo hủ tiếu gõ Sài Gòn là phải tự phi hành tím khi thắn mỡ heo để lấy dầu, khâu cuối cùng là nêm nếm cho 80 lít nước lèo (1kg bột ngọt, 50g bột nêm, 0.5kg muối, 0.5kg đường phèn, 0.5kg củ cải trắng).'),
(11, 'Xíu Mại Sốt Cà', 'image/xiu-mai-sot-ca-300x180.jpg', 'Món ăn miền Nam', '700gr thịt nạc dăm bầm nhỏ|\r\n200gr tôm bằm|\r\n150gr cá nạo|\r\n150gr tôm luộc thải nhỏ|\r\n1 muỗng cà phê muối|\r\n3 muỗng cà phê đường|\r\n3 muỗng cà phê bột ngọt|\r\n3 muỗng cà phê nước tương|\r\n2 muỗng cà phế dầu mè|\r\n1,5 muông cà phê tiêu|\r\n2 trải cà chua tỉa hoa|\r\nỚt, hành lá tía hoa, ngò|\r\n200gr củ sắn, xắt sợi, luộc sơ, bằm nhỏ, vắt ráo|\r\n20g hành lả xắt nhỏ|\r\n6 muỗng cà phê bột năng|\r\n3 muỗng cà phê tỏi phi vàng|\r\n150gr tương cà|\r\n1 muỗng súp nước màu hột điều|\r\n50gr nước leo|\r\n3 muỗng cà phô dầu mè|\r\n2 muỗng súp bột năng|\r\n2 muỗng cà phế hànli tỏi bằm nhỏ|\r\nDầu ăn – Tiêu, muối, đường, bột ngọt.', '\r\n\r\nBốn thứ cá và củ sắn trộn chung, đập cho dẻo độ 10 phút, cho gia vị ướp thịt vào đập cho đều, để nửa giờ cho thấm gia vị.|\r\n\r\n\r\n\r\nHấp xíu mại: Vo viên xíu mại bằng ngón chân cái, cho chút ngò lên, đem hấp chín độ 15 phút.\r\nLàm sốt cà: Bắc chảo dầu nóng, phi hành tỏi cho thơm, cho cà hộp và nước màu hột điều đỏ vào, xào lên cho đều, nêm chút muối, tiêu, đường, bột ngọt, cho nước lèo vào, nêm vừa ăn.\r\nBột năng hòa nước cho sốt sanh sánh, nhắc xuống cho dầu mè. Cho xíu mại ra đĩa, chế sốt lên, giữa để cá, ớt hành tỉa hoa, rắc thêm tiêu ngò cho thơm, dùng nóng với bánh mì.'),
(12, 'Cá Chẽm Chưng Tương', 'image/cachemchungtuong.jpg', 'Món ăn miền Nam', '1 con cá chẽm|\r\n1 lọn bún tàu|\r\nNấm mèo 3 – 4 cái|\r\n2 quả cà chua|\r\n1/2 củ hành tây|\r\n200g tương hột đen|\r\n¼ bắp cải|\r\n1 khúc gừng nhỏ|\r\n1 ít cần ta', 'Cho cá vào tộ hoặc tô lớn, phủ lên cá theo thứ tự bắp cải, cà chua nấm mèo, bún tàu, gừng, hành tây, cần ta. Rưới tương hột lên, nêm gia vị đường, bột nêm. Hấp khoảng 30’ khi bắp cải và cá vừa chin tới thì tắt bếp. Thường xuyên mở nắp nồi rẩy hơi nước ra ngoài\r\n\r\nKhi ăn có thể để nguyên tộ hoặc xắp cá ra dĩa là bạn có thể thưởng thức món Cá chẽm chưng tương cùng với gia đình.'),
(13, 'Canh Vịt Nấu Măng', 'image/canh vit.jpg', 'Món ăn miền Nam', 'Thịt vịt làm sẵn (1 con): 600 g|\r\nBột đao (hay bột tẻ): 1 thìa|\r\nMăng củ tươi (1 củ): 500 g|\r\nHành hoa: 2-3 cây|\r\nHành khô: 1 củ|\r\nMỡ nước (hay dầu ăn): 4-5 thìa|\r\nNước mắm, bột canh, hạt tiêu, mì chính', 'Măng tươi chọn củ thân to và ngắn, bóc bỏ bẹ ngoài, cắt bỏ phần già sơ ở gốc, thái vát móng lợn đem luộc chín, thay nhiều lượt nước, vớt ra rửa sạch để ráo.|\r\nXát muối rửa sạch nhờn ngoài da vịt, chặt miếng tương đương bao diêm, ướp nước mắm, bột canh, hạt tiêu, rắc bột rây mịn trộn đều.|\r\nĐun mỡ nóng già, phi thơm hành khô băm nhỏ, bỏ thịt vịt vào xào hơi vàng, trút sang nồi cùng với máng, đổ nước săm sắp đun sôi, nêm đủ gia vị. Đậy vung hầm nhỏ lửa, thịt vịt mềm róc xương, nêm mì chính và hành hoa thái nhỏ, để sôi lại là được. Múc vào bát to hay đĩa sâu, rắc thêm hạt tiêu. Ăn nóng'),
(14, 'Cơm Chiên Bí Đỏ', 'image/Cơm-chiên-bí-đỏ-2-400x351.jpg', 'Món ăn miền Trung', '100 g thịt nguội chay|\r\n100 g bí đỏ|\r\n100 g đậu hà lan|\r\n1 hộp bắp hạt|\r\n1 chén nho khô nhỏ|\r\n1 chén bơ thực vật|\r\nDầu mè|\r\n1 cây hành boa ro|\r\n1 gói bột ca ri|\r\n1 nhúm rau om', '\r\n\r\nĐầu tiên, bạn bắt nồi cơm|\r\nKhi cơm chín bạn dùng đũa bếp xới cho cơm tơi và cho cơm vào tủ lạnh.|\r\nThịt nguội chay cắt hạt lựu.|\r\nPhần bí đỏ gọt sạch vỏ và bỏ hạt rồi cắt miếng.|\\\r\nCho bì đỏ vào nồi và hấp mềm|\r\nCho bí đỏ vào tô và dùng muỗng tán nhuyễn.|\r\n \r\n\r\nĐậu hà lan đem rửa sạch và để ráo, còn nho khô thì cho vào nước ngâm mềm.|\r\n \r\n\r\nHành hoa ro rửa sạch và cắt nhỏ.|\r\nRau ôm, rửa sạch, bỏ gốc, cành, chỉ lấy lá.|\r\nBắc một nồi nước nhỏ lên bếp và cho đậu hà lan vào mở bếp và luộc chín.|\r\nBắc chảo lên bếp và cho phần bơ thực vật vào|\r\nĐơi khi phần bơ chảy ra thì cho hành boa ro vào phi thơm rồi cho bắp + thịt nguội chay + đậu hà lan vào xào chín và nêm vào ít gai vị cho vừa ăn.|\r\nXào rau củ|\r\n\r\nTắt bếp và cho phần nhân ra riêng một bên.|\r\nDùng lại chảo đó và làm nóng ít dầu chay|\r\nKhi dầu nóng thì cho bí đỏ vào để với bột ca ri và ít dầu mè|\r\nCho tiếp cơm vào chảo cùng với nho khô ngâm và đảo đều tay cho cơm và bí đỏ hòa với nhau.|\r\nCho tiếp phần đồ xào vào đảo đều và nên thêm ít hạt nêm chay cho vừa ăn|\r\nTắt bếp và dọn cơm ra dĩa'),
(15, 'Bún Bò Huế', 'image/bunbohue.jpg', 'Món ăn miền Trung', '2kg xương ống heo|\r\n700 gram thịt bắp bò|\r\n700 gram bắp giò heo|\r\n20 chả lá Huế|\r\n3 kg bún|\r\n100ml mắm ruốc Huế|\r\n100 gram ớt bột|\r\nGừng, sả cây, thơm|\r\nHành tây, tỏi, ớt, rau răm, hành tím|\r\nRau sống: rau muống, bắp chuối, giá đỗ|\r\nMuối, hạt tiêu, đường, hạt nêm, nước mắm, nước tương', 'Rửa sạch xương ống heo với nước lạnh. Đặt một nồi nước lạnh, bỏ ít muối đun sôi, chần qua xương ống heo rồi rửa sạch xương ống heo với nước lạnh lần hai. Đặt nồi nước khác, bỏ xương ống heo,  một muỗng muối, 2 lát xả, hầm xương trong 2 tiếng lấy nước dùng.|\r\n\r\nRau sống, bạn chọn rau muống cắt sợi, bắp chuối đã xắt và giá đỗ lược bỏ gốc, rửa sạch với nước muối, ngâm với nước đá, cho chút nước cốt chanh để rau sống ăn giòn, ngon.|\r\n\r\nSả bóc vỏ, rửa sạch, để bên ngoài 2 cây sả, còn lại để bó lát cho vào nồi hầm. Thơm cắt miếng nhỏ. Hành tây, hành tím thái nhỏ. Tỏi băm nhuyễn. Rau răm rửa sạch thái nhỏ. Ớt bột bỏ vào nước cho nở. Mắm ruốc pha chút nước loãng, khuấy đều. Chả lá Huế cắt miếng vừa ăn.|\r\n\r\nThịt bắp bò và giò heo đem rửa sạch với nước, lấy dây dù bó tròn. Đun một nồi nước, cho chút muối và xả, gừng đun sôi. Chần thịt bắp bò và giò heo qua với nước sôi rồi bỏ vào thau nước lạnh.|\r\n Ướp thịt bắp bò với gia vị trong 20 phút cho thấm. Cho chút tiêu, tỏi băm, mắm, hạt nêm, một chút dầu ăn và tương cho thịt bò mềm. Trộn đều, sau đó rắc thêm hành tím giã nhuyễn vào ướp cho thịt bò thơm, ngọt nước dùng.|\r\nBỏ thịt bò đã ướp gia vị vào nồi hầm 5 phút, sau đó mới cho giò heo vào nồi sau vì bò lâu chín hơn. Nước hầm sôi, đổ phần nước mắm ruốc khuấy đều đã chuẩn bị sẵn vào nồi. Lúc này chúng ta bỏ nguyên bó sả vào nồi để làm đậm đà hương vị.|\r\nChúng ta làm ớt sa tế bằng cách đặt chảo lên bếp, cho hành tím vào phi thơm, sau đó đổ nước ớt bột sau khi nở vào, đảo đều tay đến khi nước đặc sền sệt thì tắt bếp.|\r\nĐổ nước sa tế vào nồi hầm để làm màu nước dùng thêm ngon mắt. Lúc này chúng ta cho phần chả lá Huế vào nồi nước hầm. Bước này bạn có thể dùng nước dùng chần qua rau sống để ăn. Xong thì tắt bếp.|\r\nChần qua bún để ráo trước khi ăn. Chia bún vào bát, rải hành tây, gắp thịt bò, giò heo, chả lá Huế, rưới nước dùng vào bún, rắc tiêu và rau răm lên trang trí. Thưởng thức bát bùn bò Huế cùng rau chụng khi còn nóng các bạn nhé!\r\n\r\nXin chúc các bạn thực hiện món bún bò Huế này thành công và ngon miệng nhé!'),
(16, 'Miến Lươn', 'image/mienluonnghean.jpg', 'Món ăn miền Trung', '500g lươn tươi|\r\n2 lạng miến rong khô|\r\n300g giá đỗ|\r\n35g bột ngô|\r\n1 mớ rau răm|\r\nHành phi|\r\n½ củ hành tây to|\r\n3 củ hành củ lớn|\r\n1 củ gừng to |\r\nMuối, dầu ăn, hạt tiêu|\r\nDấm (hoặc chanh)', 'Nếu lươn nhỏ thì bạn để nguyên nhưng nếu lươn to thì thái thịt lươn thành những sợi nhỏ dài. Sau đó ướp lươn với chút muối và hạt tiêu để 10 phút cho ngấm rồi thêm bột ngô vào xóc đều.|\r\nRửa rau răm, giá đỗ và hành tây. Thái hành tây như hình.|\r\nNgâm miến trong nước khoảng 5-10 phút cho miến mềm ra.\r\nCho đầu và xương lươn vào nồi nước ninh cùng hành củ và gừng nướng để ra nước cốt ngọt chan miến. Nêm thêm muối cho vừa miệng. Khi nước bắt đầu sôi, hạ nhỏ lửa cho sôi liu riu và vớt hết sạch bọt bẩn nổi lên cho nước dùng được trong.|\r\nBắc chảo lên bếp, cho ngập dầu ăn khoảng 4-5cm. Cho từng mẻ lươn vào rán giòn đến khi lươn có màu vàng sẫm. Cho lươn ra để ráo dầu ăn.|\r\nXếp giá đỗ, hành tây và rau răm vào bát, Miến trần qua nước sôi cho thật mềm để lên trên, tiếp đó cho lươn khô vào rồi chan nước dùng. Cuối cùng rắc một ít hành phi lên trên là có thể ăn ngay rồi đó.|\r\nLưu ý khi làm món miến lươn khô giòn:|\r\nKhi chọn lươn, nhớ chọn con có da nhẵn bong và hanh vàng.|\r\nKhi lọc xương xong các bạn không được rửa lươn vào nước nữa nhé, sẽ khiến lươn bị tanh đấy.|\r\nCác bạn có thể mua thêm ít xương ống cho vào ninh cùng để nước dùng được đậm đà hơn (nếu bạn muốn nước dùng thơm hơn thì bỏ thêm mấy cánh nấm hương vào ninh cùng).\r\nKhi rán lươn, không cho quá nhiều lươn một lúc sẽ khiến lươn dính hết vào nhau, dầu sẽ mất nhiệt khiến lươn không thể giòn.|\r\nMiến lươn khô dọn ra cùng tương ớt và dấm ăn để có thật nhiều hương vị nhé.|\r\nLươn ăn không hết có thể gói kín vào túi đựng thực phẩm để ăn dần, bảo quản chỗ khô ráo, có thể dùng được 1 tháng.\r\n\r\n'),
(17, 'Chả Giò ỐC Hương ', 'image/cha-gio-oc-huong-1.jpg', 'Món ăn miền Trung', 'Ốc hương|\r\nGiò sống|\r\nNấm hương|\r\nCà rốt|\r\nKhoai lang|\r\nRượu trắng|\r\nTrứng bắc thảo|\r\nCốm xanh|\r\nTrứng gà|\r\nBánh tráng đậu xanh|\r\nTiêu xanh|\r\nGừng|\r\nHành tím băm|\r\nRượu trắng|\r\nĐường|\r\nMuối|\r\nHạt nêm|\r\nDầu ăn|\r\nRau mầm', 'Thịt ốc hương làm sạch và băm nhuyễn.|\r\nNấm hương ngâm nở, rửa sạch và băm nhỏ.|\r\nCà rốt bào vỏ, băm nhỏ.|\r\nKhoai lang gọt vỏ, rửa sạch và thái sợi nhỏ|\r\nTiêu xanh đập dập.|\r\nGừng thái chỉ.|\r\nCho tất cả nguyên liệu ở trên vào tô lớn.|\r\nCho thêm vào tô giò sống + hành tím băm nhuyễn + gia vị. Trộn đầu tô nguyên liệu để tất cả ngấm gia vị.|\r\nTrứng bắc thảo đem tán nhuyễn và cho vào tô cuối cùng.|\r\nTrải bánh tráng đậu xanh ra và cho hỗn hợp nhân lên trên mặt bánh, cuộn tròn bánh lại.|\r\nCốm xanh xay nhuyễn.|\r\nTrứng gà đánh tan.|\r\nBắt chảo lên bếp và đổ dầu vừa đủ ngập được cuốn chả giò.|\r\nNhúng từng cuốn chả giò qua trứng gà và cốm xanh rồi cho vào chảo chiên đến khi chả giò vàng đều là được.|\r\nDọn chả giò ra dĩa và ăn kèm với rau mằm + cơm trắng + nước mắm pha.'),
(18, 'Ghẹ Rang Me', 'image/gherangme.jpg', 'Món ăn miền Trung', '|Ghẹ tươi\r\nMe chín|\r\nNước mắm|\r\nMuối|\r\nĐường|\r\nỚt bột|\r\nHành lá|\r\nDầu ăn', 'Ghẹ rửa sạch, để ráo.|\r\nCho chảo lên bếp, làm nóng dầu và cho ghẹ vào chiên vàng với lửa lớ.|\r\nKhi ghẹ đã chín vàng cho ghẹ ra dĩa riêng.|\r\nMe dầm với nước sôi, bỏ bã lấy nước cốt.|\r\nCho nước cốt me vào nồi với đường + muối + nước mắm\r\nNấu sôi đến khi hỗn hợp me sánh lại.|\r\nThêm ớt và hành lá cắt nhỏ.|\r\nCho ghẹ vào hỗn hợp me và đảo đều cho đến khi ghẹ thấm đều hỗn hợp me .|\r\nTắt bếp cho ghẹ ra dĩa và dùng nóng');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbtype`
--

CREATE TABLE `tbtype` (
  `loai` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `tbtype`
--

INSERT INTO `tbtype` (`loai`, `id`) VALUES
('Món ăn miền Bắc', 0),
('Món ăn miền Nam', 0),
('Món ăn miền Trung', 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `monan2`
--
ALTER TABLE `monan2`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fsdf` (`type`);

--
-- Chỉ mục cho bảng `tbtype`
--
ALTER TABLE `tbtype`
  ADD PRIMARY KEY (`loai`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `monan2`
--
ALTER TABLE `monan2`
  MODIFY `id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `monan2`
--
ALTER TABLE `monan2`
  ADD CONSTRAINT `fsdf` FOREIGN KEY (`type`) REFERENCES `tbtype` (`loai`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
